services:
  bch-node:
    image: zquestz/bitcoin-cash-node:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./bitcoin.conf:/data/bitcoin.conf
    networks:
      bch_network:
        ipv4_address: 172.20.0.10

  bch-pool:
    build:
      context: .
      dockerfile: Dockerfile.pool
    restart: unless-stopped
    depends_on:
      - bch-node
    ports:
      - "3333:3333"
    volumes:
      - ./pool-logs:/usr/src/asicseer-pool/build/src/logs
    networks:
      bch_network:
        ipv4_address: 172.20.0.2

  bch-pool-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8091:8091"
    volumes:
      - ./pool-logs:/app/pool-logs

networks:
  bch_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
